export { getApiV1BaseUrl, request } from '@/lib/api/client'
export { ApiError, getErrorMessage, isApiError, parseApiErrorDetail } from '@/lib/api/errors'
export {
  parseTerritoryReviewError,
  TERRITORY_REVIEW_AI_UNAVAILABLE_DETAIL,
  TERRITORY_REVIEW_INVALID_LLM_SCHEMA_DETAIL,
  type ParsedTerritoryReviewError,
  type TerritoryReviewErrorKind,
} from '@/lib/api/territoryReview.errors'
export {
  createProject,
  DEFAULT_PROJECTS_LIST_LIMIT,
  DEFAULT_PROJECTS_LIST_OFFSET,
  getProjectById,
  listProjects,
  type CreateProjectPayload,
  type ListProjectsResponse,
  type Project,
} from '@/lib/api/projects'
export {
  createBlankVersion,
  forkVersion,
  getVersionById,
  listProjectVersions,
  patchVersion,
  type ListProjectVersionsResponse,
  type PatchVersionPayload,
  type ProjectVersionListItem,
  type VersionDetail,
} from '@/lib/api/versions'
export {
  cancelRun,
  createRunProgressEventSource,
  getExecutiveSummary,
  getRunExecutiveSummary,
  getRunStatus,
  parseSseEventData,
  retryRun,
  startRun,
  triggerRunDeepClearance,
} from '@/lib/api/runs'
export {
  RUN_SSE_EVENT_TYPES,
  type CancelRunResponse,
  type DeepClearanceTriggerResponse,
  type ExecutiveSummaryBriefSnapshot,
  type ExecutiveSummaryConstraintShortfallsSnapshot,
  type ExecutiveSummaryResponse,
  type ExecutiveSummaryRunSettingsSnapshot,
  type NameClearanceType,
  type NameClearanceUpdateEvent,
  type RetryRunRequestBody,
  type RunSSEEventType,
  type RunStageIndex,
  type RunState,
  type RunStatusResponse,
  type RunSummaryResponse,
  type SSEEvent,
  type StageCheckpointResponse,
  type StageCheckpointStatus,
  type StartRunRequestBody,
} from '@/lib/api/runs.types'
export {
  getNameCandidate,
  getRunNames,
  listRunNames,
  normalizeRunNamesParams,
  patchNameCandidate,
} from '@/lib/api/names'
export type {
  ClearanceRagStatus,
  DetailResponseEnvelope,
  DeepClearance,
  DomainClearanceFilterStatus,
  DomainClearanceDetailStatus,
  DomainClearance,
  DomainClearanceStatus,
  FastClearance,
  FastClearancePending,
  FastClearanceSuccess,
  FastClearanceSuccessStatus,
  FastClearanceUnknown,
  NameCandidateDeepClearanceDetailResponse,
  NameCandidateDeepDomainDetailResponse,
  NameCandidateDeepSocialDetailResponse,
  NameCandidateDeepSocialPlatformDetailResponse,
  NameCandidateDeepTrademarkDetailResponse,
  NameCandidateDeepUSPTOEvidenceRowResponse,
  NameCandidateDetailResponse,
  NameCandidateFastClearanceDetailResponse,
  NameCandidateListQueryParams,
  NameCandidateListResponse,
  NameCandidatePatchEnvelope,
  NameCandidatePatchRequest,
  NameCandidatePatchResponse,
  NameCandidateResponse,
  NameCandidateScoreCriterionResponse,
  NameCandidateScoresDetailResponse,
  NameCandidateSocialPlatform,
  NameCandidateScores,
  NameCandidateScoresCore,
  NameCandidateSortBy,
  NameCandidateSortDirection,
  NormalizedNameCandidateListQueryParams,
  NameFamily,
  NameFormat,
  SocialClearanceDetailStatus,
  SocialClearanceFilterStatus,
  SocialClearance,
  SocialClearanceMap,
  SocialClearanceStatus,
  TrademarkClearance,
  TrademarkClearanceFilterStatus,
  TrademarkClearanceStatus,
  TrademarkSimilarMark,
  USPTOEvidenceLifecycleStatus,
} from '@/lib/api/names.types'
export {
  DEFAULT_RUN_NAMES_LIST_LIMIT,
  DEFAULT_RUN_NAMES_LIST_OFFSET,
  normalizeNameCandidateListQueryParams,
} from '@/lib/api/names.types'
export {
  addTerritoryCard,
  confirmTerritoryCards,
  getResearchSnapshot,
  listTerritoryCards,
  patchTerritoryCard,
  reviseTerritoryCard,
} from '@/lib/api/territoryReview'
export type {
  AddTerritoryCardRequest,
  AddTerritoryCardResponse,
  ConfirmTerritoryCardsResponse,
  ListTerritoryCardsResponse,
  PatchTerritoryCardRequest,
  ResearchSnapshot,
  ReviseTerritoryCardRequest,
  ReviseTerritoryCardResponse,
  TerritoryCard,
  TerritoryCardData,
  TerritoryCardPatchResponse,
  TerritoryCardReviewStatus,
  ToneFingerprint,
} from '@/lib/api/territoryReview.types'
